### ISSUE TITLE
Theming & scaffolding CRUD objects

### ISSUE THREAD

**Issue by weedkiller** [salihagic/BPWAM#1]
Hello, how to scaffold CURD entities and add a theme
Also how to do master details pages in this boilerplate

**Comment by salihagic** [comment]
Hello @weedkiller, sorry for the late reply.
- Scaffolding CRUD entities is not possible at the moment, but i will look into it in the future, thanks for the idea.
- Theme is tightly coupled to this boilerplate, also needs refactoring.

As for the master details page, if i understood you correctly, you could do it by adding parameter fullPage = true to the datatable details button or at any other place when generating url for details page and attaching  data-fullpage="true" to the <a> element that is the action button.

Example:
<a href="@Url.Action("Add", "Countries", new { **fullPage = true** })" class="btn btn-brand btn-elevate btn-icon-sm" type="button">
    <i class="la la-plus"></i>
    @Translations.New_record
</a>

or

//Datatable initialization on Index page
//...
template: (row) => DatatableBasicActions({
//...
    **fullPage: true,**
}),

Ofcourse you have to remove **@{ Layout = null; }** in your respective details pages when you want full screen

Full documentation is comming soon.
